=== oracle-quickstart/oci-corrino-oke-ai-ml-toolkit/docs/custom_blueprints/prefilled_sample_json_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "payloadSchema",
  "title": "payloadSchema",
  "description": "payloadSchema",
  "type": "object",
  "properties": {
    "recipe_id": {
      "type": "string"
    },
    "deployment_name": {
      "type": "string"
    },
    "recipe_mode": {
      "enum": ["service", "job", "update", "shared_node_pool", "raycluster"]
    },
    "recipe_replica_count": {
      "type": "integer"
    },
    "recipe_node_shape": {
      "type": "string"
    },
    "recipe_max_pods_per_node": {
      "type": "integer"
    },
    "recipe_node_pool_size": {
      "type": "integer"
    },
    "recipe_use_shared_node_pool": {
      "type": "boolean"
    },
    "recipe_shared_node_pool_selector": {
      "type": "string"
    },
    "recipe_node_boot_volume_size_in_gbs": {
      "type": "integer"
    },
    "recipe_node_selector_arch": {
      "type": "string"
    },
    "recipe_flex_shape_ocpu_count": {
      "type": "integer"
    },
    "recipe_flex_shape_memory_size_in_gbs": {
      "type": "integer"
    },
    "recipe_image_uri": {
      "type": "string"
    },
    "recipe_container_command": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "recipe_container_command_args": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "recipe_container_env": {
      "type": "array",
      "items": {
        "additionalProperties": false,
        "required": ["key", "value"],
        "properties": {
          "key": {
            "type": "string"
          },
          "value": {
            "type": ["integer", "string"]
          }
        }
      }
    },
    "recipe_additional_ingress_ports": {
      "type": "array",
      "items": {
        "additionalProperties": false,
        "required": ["name", "port", "path"],
        "properties": {
          "name": {
            "type": "string"
          },
          "port": {
            "type": "integer"
          },
          "path": {
            "type": "string"
          }
        }
      }
    },
    "recipe_node_autoscaling_params": {
      "type": "object",
      "properties": {
        "min_nodes": { "type": "integer" },
        "max_nodes": { "type": "integer" }
      },
      "additionalProperties": false,
      "examples": [
        {
          "min_nodes": 1,
          "max_nodes": 2
        }
      ]
    },
    "recipe_pod_autoscaling_params": {
      "type": "object",
      "properties": {
        "min_replicas": { "type": "integer" },
        "max_replicas": { "type": "integer" },
        "scaling_metric": { "type": "string" },
        "collect_metrics_timespan": { "type": "string" },
        "scaling_threshold": { "type": "number" },
        "scaling_cooldown": { "type": "integer" },
        "polling_interval": { "type": "integer" },
        "stabilization_window_down": { "type": "integer" },
        "scaling_period_down": { "type": "integer" },
        "stabilization_window_up": { "type": "integer" },
        "scaling_period_up": { "type": "integer" },
        "query": { "type": "string" },
        "scaler_type": {
          "type": "string",
          "enum": ["prometheus"]
        },
        "server_address": { "type": "string" }
      },
      "additionalProperties": false,
      "examples": [
        {
          "min_replicas": 4,
          "max_replicas": 8,
          "scaling_metric": "e2e_request_latency_seconds_bucket",
          "collect_metrics_timespan": "1m",
          "scaling_threshold": 0.6,
          "scaling_cooldown": 60,
          "polling_interval": 15,
          "stabilization_window_down": 180,
          "scaling_period_down": 90,
          "stabilization_window_up": 120,
          "scaling_period_up": 60,
          "query": "1 - (sum(rate(vllm:e2e_request_latency_seconds_bucket{le='5.0', instance='recipe-vllmautowithfss.default:80'}[1m])) / sum(rate(vllm:e2e_request_latency_seconds_bucket{le='+Inf', instance='recipe-vllmautowithfss.default:80'}[1m])))",
          "scaler_type": "prometheus",
          "server_address": "http://prometheus-server.cluster-tools.svc.cluster.local"
        }
      ]
    },
    "recipe_liveness_probe_params": {
      "type": "object",
      "properties": {
        "failure_threshold": { "type": "number" },
        "endpoint_path": { "type": "string" },
        "port": { "type": "integer" },
        "scheme": { "type": "string" },
        "initial_delay_seconds": { "type": "number" },
        "period_seconds": { "type": "number" },
        "success_threshold": { "type": "integer" },
        "timeout_seconds": { "type": "number" }
      },
      "additionalProperties": false
    },
    "recipe_startup_probe_params": {
      "type": "object",
      "properties": {
        "failure_threshold": { "type": "number" },
        "endpoint_path": { "type": "string" },
        "port": { "type": "integer" },
        "scheme": { "type": "string" },
        "initial_delay_seconds": { "type": "number" },
        "period_seconds": { "type": "number" },
        "success_threshold": { "type": "integer" },
        "timeout_seconds": { "type": "number" }
      },
      "additionalProperties": false
    },
    "recipe_container_port": {
      "type": "string"
    },
    "recipe_container_command_use_shell": {
      "type": "boolean"
    },
    "recipe_nvidia_gpu_count": {
      "type": "integer"
    },
    "recipe_amd_gpu_count": {
      "type": "integer"
    },
    "recipe_shared_memory_volume_size_limit_in_mb": {
      "type": "integer"
    },
    "recipe_ephemeral_storage_size": {
      "type": "integer"
    },
    "recipe_container_memory_size": {
      "type": "integer"
    },
    "input_object_storage": {
      "type": "array",
      "items": {
        "additionalProperties": false,
        "oneOf": [
          {
            "required": ["par", "mount_location", "volume_size_in_gbs"]
          },
          {
            "required": ["bucket_name", "mount_location", "volume_size_in_gbs"]
          }
        ],
        "properties": {
          "par": {
            "type": "string"
          },
          "bucket_name": {
            "type": "string"
          },
          "mount_location": {
            "type": "string"
          },
          "volume_size_in_gbs": {
            "type": "integer"
          },
          "include": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "exclude": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "input_file_system": {
      "type": "array",
      "items": {
        "additionalProperties": false,
        "required": [
          "file_system_ocid",
          "mount_target_ocid",
          "mount_location",
          "volume_size_in_gbs"
        ],
        "properties": {
          "file_system_ocid": {
            "type": "string"
          },
          "mount_target_ocid": {
            "type": "string"
          },
          "mount_location": {
            "type": "string"
          },
          "volume_size_in_gbs": {
            "type": "integer"
          }
        }
      }
    },
    "output_object_storage": {
      "type": "array",
      "items": {
        "additionalProperties": false,
        "required": ["bucket_name", "mount_location", "volume_size_in_gbs"],
        "properties": {
          "bucket_name": {
            "type": "string"
          },
          "mount_location": {
            "type": "string"
          },
          "volume_size_in_gbs": {
            "type": "integer"
          }
        }
      }
    },
    "service_endpoint_domain": {
      "type": "string"
    },
    "service_endpoint": {
      "type": "object",
      "properties": {
        "domain": {
          "type": "string"
        },
        "dedicated_load_balancer": {
          "type": "boolean"
        }
      }
    },
    "shared_node_pool_selector": {
      "type": "string"
    },
    "shared_node_pool_size": {
      "type": "integer"
    },
    "shared_node_pool_shape": {
      "type": "string"
    },
    "shared_node_pool_boot_volume_size_in_gbs": {
      "type": "integer"
    },
    "shared_node_pool_flex_shape_memory_size_in_gbs": {
      "type": "integer"
    },
    "shared_node_pool_flex_shape_ocpu_count": {
      "type": "integer"
    },
    "shared_node_pool_mig_config": {
      "type": "string"
    },
    "mig_resource_request": {
      "type": "string"
    },
    "recipe_node_name": {
      "type": "string"
    },
    "recipe_node_labels": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "recipe_node_pool_name": {
      "type": "string"
    },
    "skip_capacity_validation": {
      "type": "boolean"
    },
    "skip_quota_validation": {
      "type": "boolean"
    },
    "recipe_raycluster_params": {
      "type": "object",
      "properties": {
        "head_node_num_cpus": {
          "type": "integer"
        },
        "head_node_num_gpus": {
          "type": "integer"
        },
        "head_node_cpu_mem_in_gbs": {
          "type": "integer"
        },
        "num_worker_nodes": {
          "type": "integer"
        },
        "worker_node_num_cpus": {
          "type": "integer"
        },
        "worker_node_num_gpus": {
          "type": "integer"
        },
        "worker_node_cpu_mem_in_gbs": {
          "type": "integer"
        },
        "model_path_in_container": {
          "type": "string"
        },
        "redis_port": {
          "type": "integer"
        },
        "dashboard_port": {
          "type": "integer"
        },
        "metrics_export_port": {
          "type": "integer"
        },
        "rayclient_server_port": {
          "type": "integer"
        },
        "worker_image_uri": {
          "type": "string"
        },
        "head_image_uri": {
          "type": "string"
        },
        "rayjob_image_uri": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "head_node_num_cpus",
        "head_node_num_gpus",
        "head_node_cpu_mem_in_gbs",
        "num_worker_nodes",
        "worker_node_num_cpus",
        "worker_node_num_gpus",
        "worker_node_cpu_mem_in_gbs"
      ]
    }
  },
  "required": ["recipe_mode", "deployment_name"],
  "additionalProperties": false
}

=== oracle-quickstart/oci-corrino-oke-ai-ml-toolkit/docs/auto_scaling/example_recipe.json
{
    "recipe_id": "llm_inference_nvidia",
    "recipe_mode": "service",
    "deployment_name": "autoscale_vllm_example",
    "recipe_image_uri": "iad.ocir.io/iduyx1qnmway/corrino-devops-repository:vllmv0.6.5",
    "recipe_node_shape": "VM.GPU.A10.2",
    "recipe_replica_count": 1,
    "recipe_container_port": "8000",
    "recipe_nvidia_gpu_count": 1,
    "recipe_container_command_args": [
        "--model",
        "NousResearch/Meta-Llama-3.1-8B-Instruct",
        "--tensor-parallel-size",
        "1",
        "--gpu-memory-utilization",
        "0.99",
        "--max-model-len",
        "4096"
    ],
    "recipe_ephemeral_storage_size": 200,
    "recipe_node_boot_volume_size_in_gbs": 300,
    "recipe_node_pool_size": 1,
    "recipe_shared_memory_volume_size_limit_in_mb": 200,
    "recipe_startup_probe_params": {
      "failure_threshold": 30,
      "endpoint_path": "/health",
      "port": 8000,
      "scheme": "HTTP",
      "initial_delay_seconds": 60,
      "period_seconds": 2,
      "success_threshold": 1,
      "timeout_seconds": 1
    },
    "recipe_liveness_probe_params": {
      "failure_threshold": 1,
      "endpoint_path": "/health",
      "port": 8000,
      "scheme": "HTTP",
      "initial_delay_seconds": 65,
      "period_seconds": 600,
      "success_threshold": 1,
      "timeout_seconds": 1
    },
    "recipe_pod_autoscaling_params": {
      "min_replicas": 1,
      "max_replicas": 4,
      "scaling_threshold": 0.1
    },
    "recipe_node_autoscaling_params": {
      "min_nodes": 1,
      "max_nodes": 2
    }
}

=== oracle-quickstart/oci-corrino-oke-ai-ml-toolkit/docs/sample_blueprints/mig_inference_single_replica_10gb.json
{
    "recipe_id": "llm_inference_nvidia",
    "recipe_mode": "service",
    "deployment_name": "autoscale_mig",
    "recipe_image_uri": "iad.ocir.io/iduyx1qnmway/corrino-devops-repository:vllmv0.6.5",
    "recipe_node_shape": "BM.GPU.H100.8",
    "recipe_container_env": [
    {
        "key": "tensor_parallel_size",
        "value": "1"
    },
    {
      "key": "HF_TOKEN",
      "value": "<hf_token>"
    }
    ],
    "recipe_replica_count": 1,
    "recipe_container_port": "8000",
    "recipe_nvidia_gpu_count": 1,
    "recipe_use_shared_node_pool": true,
    "mig_resource_request": "1g.10gb",
    "recipe_container_command_args": [
        "--model",
        "meta-llama/Llama-3.2-3B-Instruct",
        "--dtype",
        "bfloat16",
        "--tensor-parallel-size",
        "$(tensor_parallel_size)",
        "--gpu-memory-utilization",
        "0.99",
        "--max-model-len",
        "16384"
    ],
    "recipe_ephemeral_storage_size": 30,
    "recipe_node_boot_volume_size_in_gbs": 300,
    "recipe_shared_memory_volume_size_limit_in_mb": 1000,
    "recipe_startup_probe_params": {
      "failure_threshold": 30,
      "endpoint_path": "/health",
      "port": 8000,
      "scheme": "HTTP",
      "initial_delay_seconds": 10,
      "period_seconds": 2,
      "success_threshold": 1,
      "timeout_seconds": 1
    },
    "recipe_liveness_probe_params": {
      "failure_threshold": 3,
      "endpoint_path": "/health",
      "port": 8000,
      "scheme": "HTTP",
      "initial_delay_seconds": 65,
      "period_seconds": 600,
      "success_threshold": 1,
      "timeout_seconds": 1
    },
    "recipe_pod_autoscaling_params": {
      "min_replicas": 1,
      "max_replicas": 50
    }
}
